//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Hall_Booking_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string userName { get; set; }
        public string pass { get; set; }
        public string email { get; set; }
        public decimal mobile { get; set; }
    }
}
