//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Hall_Booking_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBooking
    {
        public string name { get; set; }
        public string email { get; set; }
        public decimal mobile { get; set; }
        public string roomCategory { get; set; }
        public System.DateTime meetingDate { get; set; }
        public string address { get; set; }
        public string description { get; set; }
    }
}
